"use client"

import { Button } from "@/components/ui/button"
import { Download } from "lucide-react"
import jsPDF from "jspdf"

export function RequestReceiptButton({ request, generatedBy }: { request: any, generatedBy: string }) {
    const handleDownloadPDF = async () => {
        const doc = new jsPDF()

        // --- Logo ---
        // Load image from URL to base64 or just draw it if possible
        // Ideally we should load it once. For simplicity we'll try adding it directly.
        // If image loading fails, we'll skip it or show text.
        try {
            const img = new Image()
            img.src = "/assets/expressway.png"
            await new Promise((resolve, reject) => {
                img.onload = resolve
                img.onerror = reject
            })
            // Add logo: x, y, w, h
            doc.addImage(img, "PNG", 15, 10, 20, 20)
        } catch (e) {
            console.error("Failed to load logo", e)
        }

        // --- Header ---
        doc.setFontSize(18)
        doc.setFont("helvetica", "bold")
        doc.text("ETC Information Document", 105, 23, { align: "center" })

        doc.setFontSize(10)
        doc.setFont("helvetica", "normal")
        doc.text("Electronic Toll Collection System", 105, 29, { align: "center" })

        doc.setLineWidth(0.5)
        doc.line(15, 35, 195, 35)

        // --- Content ---
        let y = 50
        const leftX = 20
        const valueX = 70

        const addRow = (label: string, value: string) => {
            doc.setFont("helvetica", "bold")
            doc.text(label, leftX, y)
            doc.setFont("helvetica", "normal")
            doc.text(value || "N/A", valueX, y)
            y += 10
        }

        addRow("Request No (Token):", request.requestNo)
        addRow("Applicant Name:", request.applicantName)
        addRow("NIC / Passport:", request.applicantNICOrPassport)
        addRow("Mobile Number:", request.applicantMobile)
        addRow("Email Address:", request.applicantEmail)

        y += 5 // Spacer

        if (request.companyName) {
            addRow("Company Name:", request.companyName)
            if (request.brn) {
                addRow("BRN:", request.brn)
            }
        }

        y += 5 // Spacer

        addRow("Vehicle LPN:", request.lpn)
        addRow("Vehicle Type:", typeof request.vehicleType === 'object' ? request.vehicleType.label : request.vehicleType)

        if (request.rfidValue) {
            addRow("RFID Tag:", request.rfidValue)
        }

        if (request.preferredLocation) {
            addRow("Location:", request.preferredLocation.name || "N/A")
        }

        // --- Acknowledgement Section ---
        y += 20

        // Box for acknowledgement
        doc.setLineWidth(0.3)
        doc.rect(15, y, 180, 50)

        const boxY = y
        y += 10

        doc.setFontSize(11)
        doc.setFont("helvetica", "bold")
        doc.text(`Acknowledgement of Installation, of ETC for Vehicle ${request.lpn}`, 105, y, { align: "center" })

        y += 30

        // Signature Line
        doc.line(25, y, 95, y) // Line for name/signature

        y += 5
        doc.setFontSize(9)
        doc.setFont("helvetica", "normal")
        doc.text("Name & Signature", 25, y)
        doc.text("(If name is not present, manually write behalf person name)", 25, y + 4)


        // --- Footer ---
        doc.setFontSize(8)
        doc.setTextColor(100)
        y = 280
        doc.text("This document was generated electronically.", 105, y, { align: "center" })
        doc.text(`Generated by: ${generatedBy}`, 105, y + 4, { align: "center" })
        doc.text(`Generated on: ${new Date().toLocaleString()}`, 105, y + 8, { align: "center" })

        // Save
        doc.save(`ETC_Receipt_${request.requestNo}.pdf`)
    }

    return (
        <Button variant="outline" size="sm" className="gap-2" onClick={handleDownloadPDF}>
            <Download className="h-4 w-4" />
            Export Receipt
        </Button>
    )
}
